# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models


def create_customers(apps, schema_editor):
    Customer = apps.get_model('invoices', 'Customer')
    Customer.objects.create(name='John Doe', address='Some street\nSome town')
    Customer.objects.create(name='Apple', address='Other street\nOther town')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RunPython(create_customers),
    ]
